language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - sudo apt-get update -qq

# command to install dependencies
install: "pip install -r travis-requirements.txt --use-mirrors"

# command to run tests
script: "unit2 discover"

notifications:
  email: "john.g.evans.ne@gmail.com"
